import serial
from io import StringIO
import numpy as np
import matplotlib.pyplot as plt

#ser = serial.Serial('/dev/cu.usbmodem1421', baudrate=9600, timeout=5)
ser = serial.Serial('COM3', baudrate=9600, timeout=5)

data_received = False
while not data_received:
    line = ser.readline().decode('utf-8')
    if line.startswith("log: "):
        print("ARDUINO {}".format(line[5:].rstrip()))
    elif line.startswith("data: "):
        t = np.loadtxt(StringIO(line[6:]))
        #t *= 1e-6

        s = np.empty(len(t))
        s[::2] = 0
        s[1::2] = 1

        plt.xlabel("Time $us$")
        plt.ylabel("Value")
        plt.step(t, s, where='post')
        plt.ylim(-0.5, 1.5)
        plt.show()
        plt.close()

        np.savetxt(
            "capture.csv", 
            t,
            fmt='%u',
            delimiter=' ', 
            header='Generated by https://github.com/cheind/arduino-infrared')

        data_received = True

ser.close()